### ISSUE TITLE
مبهم بودن نحوه استفاده

### ISSUE THREAD

**Issue by mreza-mohammadzadeh** [M-amir-M/persian-datetime-picker#47]
سلام وقت بخیر ممنون بابت پکیج خوبتون ولی متاسفانه نتونستم ازش استفاده کنم چون دقیق نحوه استفاده ذکر نکردید example هاش مبهم بود برای من
مثلا این یه نمونه از مثال ها بود که معلوم نیست اینو چطوری توی ui استفاده کنیم و اینکه persianFormat این ارور میده اگه امکانش هست براتون نحوه استفاده ش رو کامل تر کنید تا برای من مبتدی هم بتونم راحت ازش استفاده کنم
var picked = await showTimePicker(
  context: context,
  initialTime: TimeOfDay.now(),
);
var label = picked.persianFormat(context);

**Comment by makhloughi** [comment]
yes their examples in the readme are not clear and everything begins in the middle of the app and that's not helping others and not fulfill the goal of the example and readme section.
and that's interesting they put just a label on this issue and left it. not changes made yet

**Comment by liuzhebaba** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
wonkim, @anmolduainter, @nerdycat, @manucheri, @nam-dh, @kbanglore, @chuxiaonan, @HuyangJake, @hujiwei, @Radagaisus, @tianzhihao, @paulgalarza, @Eastkap, @huobaolajiao, @YK-Yash, @shenqiwen, @virzak, @Dn-a, @mgenware, @wxh154954803

**Comment by M-amir-M** [comment]
I appreciate your feedback. I’ve now improved the examples in the README for better clarity and flow, ensuring they start from the beginning of the app to fulfill the intended goals. If there’s any part that’s still unclear, please let me know!
